export const MONEY = '💵';
export const TURNS = '⏰';
export const LUCK = '🍀';
export const MULT = '❎';
export const REFRESH = '🔀';
export const BUY = '✅';
export const RESEARCH_POINT = '🧬';

export const CATEGORY_EMPTY_SPACE = Symbol('Empty Space');
export const CATEGORY_UNBUYABLE = Symbol('Unbuyable');
export const CATEGORY_ANIMAL = Symbol('Animal');
export const CATEGORY_FOOD = Symbol('Food');
export const CATEGORY_FRUIT = Symbol('Fruit');
export const CATEGORY_VEGETABLES = Symbol('Vegetables');
export const CATEGORY_GAMBLING = Symbol('Gambling');
export const CATEGORY_BUSINESS = Symbol('Business');
export const CATEGORY_RESEARCH = Symbol('Research');

export const PACK_BASE = Symbol('Base');
export const PACK_CASINO = Symbol('Casino');
export const PACK_FACTORY = Symbol('Factory');
export const PACK_FARM = Symbol('Farm');
export const PACK_LUCK = Symbol('Luck');
export const PACK_MAGIC = Symbol('Magic');
export const PACK_MONEY = Symbol('Money');
export const PACK_MUSIC = Symbol('Music');
export const PACK_PARTY = Symbol('Party');
export const PACK_ROCK = Symbol('Rock');
export const PACK_SHOP = Symbol('Shop');
